name: Demo CI

on: 
  workflow_dispatch:

jobs:
  run-test:
    name: 'Run tests'
    runs-on: ubuntu-latest

    steps: 
      - name: Git clone
        uses: actions/checkout@v4

      - name: User Node.js 18.16.0
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0

      - name: NPM install
        run: npm ci

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker start
        run: docker run -v ${PWD}:/e2e -w /e2e --rm  cypress/included:13.6.2 -s cypress/e2e -b chrome

      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
